-- ============================================================
-- CyberGuard AI - Seed Data
-- Run AFTER schema.sql
-- Passwords are bcrypt hashes of "Test1234!"
-- ============================================================

-- Test User 1
INSERT INTO users (id, email, hashed_password, is_active, is_verified, role)
VALUES (
    'a1b2c3d4-0000-0000-0000-000000000001',
    'alice@cyberguard.dev',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TsuBZgWXiB0h9yExgHGvqzCvqGC6',
    TRUE, TRUE, 'analyst'
) ON CONFLICT (email) DO NOTHING;

INSERT INTO user_profiles (user_id, full_name, phone, timezone)
VALUES (
    'a1b2c3d4-0000-0000-0000-000000000001',
    'Alice Chen',
    '+1-555-0101',
    'America/New_York'
) ON CONFLICT (user_id) DO NOTHING;

INSERT INTO user_settings (user_id, email_notifications, sms_notifications, critical_alerts, high_alerts, medium_alerts, low_alerts)
VALUES (
    'a1b2c3d4-0000-0000-0000-000000000001',
    TRUE, FALSE, TRUE, TRUE, FALSE, FALSE
) ON CONFLICT (user_id) DO NOTHING;

-- Test User 2
INSERT INTO users (id, email, hashed_password, is_active, is_verified, role)
VALUES (
    'b2c3d4e5-0000-0000-0000-000000000002',
    'bob@cyberguard.dev',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TsuBZgWXiB0h9yExgHGvqzCvqGC6',
    TRUE, TRUE, 'user'
) ON CONFLICT (email) DO NOTHING;

INSERT INTO user_profiles (user_id, full_name, phone, timezone)
VALUES (
    'b2c3d4e5-0000-0000-0000-000000000002',
    'Bob Martinez',
    '+44-20-7946-0101',
    'Europe/London'
) ON CONFLICT (user_id) DO NOTHING;

INSERT INTO user_settings (user_id, email_notifications, critical_alerts, high_alerts)
VALUES (
    'b2c3d4e5-0000-0000-0000-000000000002',
    TRUE, TRUE, TRUE
) ON CONFLICT (user_id) DO NOTHING;

-- Devices for User 1 (Alice)
INSERT INTO devices (user_id, name, ip_address, mac_address, device_type, os_type, status)
VALUES
    ('a1b2c3d4-0000-0000-0000-000000000001', 'Web-Server-01',    '192.168.1.10', 'AA:BB:CC:DD:EE:01', 'server',      'Ubuntu 22.04 LTS', 'active'),
    ('a1b2c3d4-0000-0000-0000-000000000001', 'DB-Server-01',     '192.168.1.11', 'AA:BB:CC:DD:EE:02', 'server',      'CentOS 8',         'active'),
    ('a1b2c3d4-0000-0000-0000-000000000001', 'Workstation-Alice', '192.168.1.50', 'AA:BB:CC:DD:EE:03', 'workstation', 'Windows 11',       'active'),
    ('a1b2c3d4-0000-0000-0000-000000000001', 'Edge-Router-01',   '192.168.1.1',  'AA:BB:CC:DD:EE:04', 'router',      NULL,               'active'),
    ('a1b2c3d4-0000-0000-0000-000000000001', 'Firewall-01',      '192.168.1.2',  'AA:BB:CC:DD:EE:05', 'firewall',    'pfSense 2.7',      'active');

-- Devices for User 2 (Bob)
INSERT INTO devices (user_id, name, ip_address, mac_address, device_type, os_type, status)
VALUES
    ('b2c3d4e5-0000-0000-0000-000000000002', 'App-Server-01',  '10.0.0.10', 'BB:CC:DD:EE:FF:01', 'server',      'Debian 12',        'active'),
    ('b2c3d4e5-0000-0000-0000-000000000002', 'Dev-Machine-01', '10.0.0.50', 'BB:CC:DD:EE:FF:02', 'workstation', 'macOS Sonoma',     'active'),
    ('b2c3d4e5-0000-0000-0000-000000000002', 'IoT-Sensor-01',  '10.0.0.100','BB:CC:DD:EE:FF:03', 'iot',         'Embedded Linux',   'active');

-- ============================================================
-- End of Seed Data
-- NOTE: Threats and notifications will be generated by the
-- simulation service automatically after startup.
-- ============================================================
